name: Mon premier workflow
on: push

jobs:
  testdocker:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v6
      - run: ls -la 
      - run: node -v