name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ::group::mon groupe
        echo 1
        echo 2
        echo 3
        echo 4
        echo ::endgroup::
      
      
      
